import{a as y,i as u,S as b}from"./assets/vendor-u8rapaCG.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const L="46122633-b5d9525daa165f05b8fce4913",F="https://pixabay.com/api/";async function w(e,s=1){const i=`${F}?key=${L}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${s}`;try{const{data:o}=await y.get(i);return o}catch(o){throw console.error("Error fetching images:",o),o}}function E(e){const s=document.querySelector(".gallery"),i=e.map(({webformatURL:o,largeImageURL:t,tags:r,likes:a,views:h,comments:g,downloads:p})=>`
      <li class="gallery-item">
        <a href="${t}">
          <img src="${o}" alt="${r}" loading="lazy" class="images"/>
        </a>
        <div class="info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${h}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${p}</p>
        </div>
      </li>
    `).join("");s.insertAdjacentHTML("beforeend",i)}function f(e){u.error({message:e,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",close:!0})}function v(e){u.info({message:e,position:"topRight",backgroundColor:"#EF4040",messageColor:"#FFFFFF",close:!0})}const $=document.getElementById("search-form"),B=document.querySelector(".gallery"),n=document.getElementById("loader");let I=new b(".gallery a");const c=document.getElementById("load-more");let l=1,d="";n.classList.add("is-hidden");$.addEventListener("submit",async e=>{if(e.preventDefault(),d=e.currentTarget.elements.searchQuery.value.trim(),l=1,!d){f("Please enter a search term.");return}B.innerHTML="",c.classList.add("hidden"),n.classList.remove("is-hidden"),await m(),n.classList.add("is-hidden")});async function m(){try{const e=await w(d,l);E(e.hits),I.refresh(),C(e.hits.length),l*15>=e.totalHits&&(v("We're sorry, but you've reached the end of search results."),c.classList.add("hidden"))}catch{f("Failed to load images.")}}function C(e){e<15?c.classList.add("hidden"):c.classList.remove("hidden")}c.addEventListener("click",async()=>{l+=1,n.classList.remove("is-hidden"),await m(),n.classList.add("is-hidden"),P()});function P(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
