import{a as y}from"./assets/vendor-Cn2Vr82J.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function l(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=l(r);fetch(r.href,s)}})();const g="46122633-b5d9525daa165f05b8fce4913",h="https://pixabay.com/api/";async function f(e,t){return(await y.get(h,{params:{key:g,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}function p(e){const t=document.querySelector(".gallery"),l=e.map(o=>`
        <li class="gallery-item">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${o.likes}</p>
            <p><b>Views:</b> ${o.views}</p>
            <p><b>Comments:</b> ${o.comments}</p>
            <p><b>Downloads:</b> ${o.downloads}</p>
          </div>
        </li>`).join("");t.insertAdjacentHTML("beforeend",l)}function b(){const e=document.querySelector(".gallery");e.innerHTML=""}const L=document.querySelector("#search-form"),m=document.querySelector(".load-more"),w=document.querySelector(".loader");let a="",n=1,d=0;L.addEventListener("submit",S);m.addEventListener("click",q);async function S(e){if(e.preventDefault(),a=e.currentTarget.elements.searchQuery.value.trim(),!a){alert("Please enter a search query");return}n=1,b(),c(!0),u(!1);try{const t=await f(a,n);d=t.totalHits,t.hits.length===0?alert("No images found"):(p(t.hits),d>n*15&&u(!0))}catch(t){console.error("Error:",t.message)}finally{c(!1)}}async function q(){n+=1,c(!0);try{const e=await f(a,n),t=window.scrollY;p(e.hits);const o=document.querySelector(".gallery").scrollHeight;window.scrollTo({top:t+(o-t),behavior:"smooth"}),n*15>=d&&(u(!1),alert("You've reached the end of search results"))}catch(e){console.error("Error:",e.message)}finally{c(!1)}}function c(e){w.classList.toggle("hidden",!e)}function u(e){m.classList.toggle("hidden",!e)}
//# sourceMappingURL=index.js.map
